# Your Solution

version: '3'
services:

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    # volumes:
    #   - ./book-catalog:usr/src/app:z
    ports:
      - "4001:80"
    environment:
      - PORT=80
    restart: "no"

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    # volumes:
    #   - ./inventory-management:usr/src/app:z
    ports:
      - "4002:80"
    environment:
      - PORT=80
    restart: "no"